### ISSUE TITLE
A missing file in the project

### ISSUE THREAD

**Issue by v3551G** [YyzHarry/multi-domain-imbalance#4]
In the  file 'mdlt/scripts/download.py',  there is a file  "scripts/misc/domain_net_duplicates.txt" required. Can you provide this file?

**Comment by YyzHarry** [comment]
Hi - thanks for spotting the issue. The file has been [uploaded here](https://github.com/YyzHarry/multi-domain-imbalance/blob/main/mdlt/scripts/misc/domain_net_duplicates.txt).
